version: "2"
linters:
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errchkjson
    - fatcontext
    - gocheckcompilerdirectives
    - gochecksumtype
    - gomodguard
    - gosmopolitan
    - loggercheck
    - makezero
    - musttag
    - nilerr
    - nilnesserr
    - perfsprint
    - prealloc
    - protogetter
    - reassign
    - recvcheck
    - spancheck
    - testifylint
    - zerologlint
  disable:
    - depguard
    - errorlint
    - exhaustive
    - gosec
    - noctx
    - rowserrcheck
    - sqlclosecheck
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
